exports.seed = function(knex) {
 
    return knex('doggos').insert([
  
      { doggo: "Tyson", age: 2, breed:"Chihuahua", picture1:"https://pet-uploads.adoptapet.com/a/8/2/363003064.jpg", description: "Tyson is a cute 7lb ball of love!! It takes a moment for this boy to get to know you, but once he does he's all kisses and cuddles!!", picture2: "https://pet-uploads.adoptapet.com/e/5/0/363003070.jpg", picture3: "https://pet-uploads.adoptapet.com/7/4/8/363003075.jpg"},     
      { doggo: "Coco", age: 7, breed:"Siberian Husky", picture1:"https://pet-uploads.adoptapet.com/c/0/6/378717100.jpg", description: "Coco is a 2 year-old Husky/Malamute mix who has gone through collar recall training. He is an active guy who needs the same in his forever home.", picture2: "https://pet-uploads.adoptapet.com/2/5/e/378717095.jpg", picture3: "https://pet-uploads.adoptapet.com/c/4/6/378717121.jpg"},
      { doggo: "Nicky", age: 4, breed:"Anatolian Scheperd", picture1:"https://pet-uploads.adoptapet.com/5/b/8/421886147.jpg", description: "Nicky weighs about 80 lbs, is 2-3 yrs old. She is shy at first, but will warm up when she's comfortable.", picture2: "https://pet-uploads.adoptapet.com/5/c/a/421886153.jpg", picture3: "https://pet-uploads.adoptapet.com/4/7/a/421886158.jpg"},
      { doggo: "Brown", age: 1, breed:"Shepherd (Unknown Type)/Labrador Retriever Mix", picture1:"https://pet-uploads.adoptapet.com/9/a/f/415201292.jpg", description:"Brown is an amazing girl!! She loves going on hikes and loves to go to the beach and play in the water. She also will play fetch and will bring the ball back right to your hand. ", picture2:"https://pet-uploads.adoptapet.com/5/3/8/415201305.jpg", picture3: "https://pet-uploads.adoptapet.com/d/2/9/415201299.jpg"},
      { doggo: "Seth", age: 6, breed:"Chihuahua/Italian Greyhound Mix", picture1:"https://pet-uploads.adoptapet.com/0/e/b/410809475.jpg", description: "Seth is our lanky, long-legged, gorgeous Chihuahua/Italian Greyhound mix. He is currently being fostered in a home with other small dogs, but Seth would prefer to be the king of the castle and be the only dog in the home.", picture2: "https://pet-uploads.adoptapet.com/6/d/b/410809462.jpg", picture3: "https://pet-uploads.adoptapet.com/c/a/0/410809469.jpg"},
      { doggo: "Charlie", age: 11, breed:"Chihuahua", picture1:"https://pet-uploads.adoptapet.com/8/6/5/491945949.jpg", description: "Charlie is a dream dog he will cuddle with you and sleep under any blankets and if you take a little bal out he will be ready to play. He brings the ball back and will keep you laughing all day.", picture2: "https://pet-uploads.adoptapet.com/3/c/1/491945977.jpg", picture3: "https://pet-uploads.adoptapet.com/d/f/6/491945955.jpg"},
      { doggo: "Janey", age: 4, breed:"Miniature Pinscher", picture1:"https://www.pethealthnetwork.com/sites/default/files/content/images/miniature-pinscher178474728.png", description: "Janey is a very friendly and confident girl Very interactive with other dogs and people.  She is leash and crate trained.", picture2: "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/10114103/Miniature-Pinscher-leaping-through-a-meadow.jpg", picture3: "https://pet-uploads.adoptapet.com/6/4/b/421906792.jpg"},
      { doggo: "Cicero", age: 9, breed:"Chihuahua/Dachshund Mix", picture1:"https://pet-uploads.adoptapet.com/b/3/b/421906783.jpg", description: "Cicero is a friendly, happy guy who loves going on walks and hanging out with his foster family. Cicero is currently being fostered in home with other dogs and children.", picture2: "https://pet-uploads.adoptapet.com/b/3/b/421906783.jpg", picture3: "https://pet-uploads.adoptapet.com/b/1/4/421906756.jpg"},

    ]);
  
  };